# Generated by Django 3.1.6 on 2023-01-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230126_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Napitak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('cijena', models.IntegerField()),
                ('drzava', models.CharField(max_length=100)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sladoled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('datum_proizvodnje', models.DateField()),
                ('vegan', models.BooleanField()),
                ('cijena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sladoledni_kup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('cijena', models.IntegerField()),
                ('opis', models.TextField()),
                ('sladoled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sladoled')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
