# Generated by Django 5.1.2 on 2024-11-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_budzet_kategorija_prihod_budzet_rashod_budzet_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budzet',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='budzet',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budzet', to='main.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Kategorija',
        ),
    ]
