# Generated by Django 4.1.12 on 2023-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_auto_20230126_0135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="napitak",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sladoled",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sladoledni_kup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
