# Generated by Django 5.1.2 on 2024-11-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_budzet_kategorija_prihod_rashod_delete_napitak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budzet',
            name='kategorija',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budzet', to='main.kategorija'),
        ),
        migrations.AddField(
            model_name='prihod',
            name='budzet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prihodi', to='main.budzet'),
        ),
        migrations.AddField(
            model_name='rashod',
            name='budzet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rashodi', to='main.budzet'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('budzeti', models.ManyToManyField(blank=True, related_name='tagovi', to='main.budzet')),
                ('prihodi', models.ManyToManyField(blank=True, related_name='tagovi', to='main.prihod')),
                ('rashodi', models.ManyToManyField(blank=True, related_name='tagovi', to='main.rashod')),
            ],
        ),
    ]
