# Generated by Django 5.1.2 on 2025-01-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_budzet_kategorija_budzet_tag_tag_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prihod',
            name='budzet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.budzet'),
        ),
    ]
